/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface GenerationLog {
  brandImages: string;
  candidates: string | null;
  createdAt: Generated<string>;
  id: string | null;
  modelName: string;
  productCategory: string;
  productName: string;
  prompt: string;
  provider: string;
  story: string | null;
  targetUserImage: string;
  temperature: number;
  usageCompletionTokens: number;
  usagePromptTokens: number;
  usageTotalTokens: number;
}

export interface LandingPage {
  config: string;
  createdAt: Generated<string>;
  deletedAt: string | null;
  generationLogId: string;
  htmlContent: string | null;
  id: string | null;
  isPublic: Generated<number | null>;
  metadata: Generated<string | null>;
  ogImageUrl: string | null;
  selectedCopies: string;
  shareUrl: string | null;
  templateId: string;
  title: string;
  updatedAt: Generated<string>;
  viewCount: Generated<number | null>;
}

export interface LpTemplate {
  baseHtml: string;
  category: string | null;
  createdAt: Generated<string>;
  defaultConfig: string;
  description: string | null;
  id: string | null;
  isActive: Generated<number | null>;
  name: string;
  thumbnailUrl: string | null;
}

export interface LpView {
  id: string | null;
  ipAddress: string | null;
  landingPageId: string;
  referrer: string | null;
  userAgent: string | null;
  viewedAt: Generated<string>;
}

export interface DB {
  generationLogs: GenerationLog;
  landingPages: LandingPage;
  lpTemplates: LpTemplate;
  lpViews: LpView;
}
