/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface GenerationLog {
  brandImages: string;
  candidates: string | null;
  createdAt: Generated<string>;
  id: string | null;
  modelName: string;
  productCategory: string;
  productName: string;
  prompt: string;
  provider: string;
  story: string | null;
  targetUserImage: string;
  temperature: number;
  usageCompletionTokens: number;
  usagePromptTokens: number;
  usageTotalTokens: number;
}

export interface DB {
  generationLogs: GenerationLog;
}
